name: followers
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  get: ^4.6.5
  dio_cookie_manager: ^3.1.0
  cookie_jar: ^4.0.5
  dio: ^5.2.1+1
  flutter_screenutil: ^5.8.4
  firebase_auth: ^4.10.0
  firebase_core: ^2.15.0
  shimmer: ^3.0.0
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  country_pickers: ^2.0.0
  image_picker: ^1.0.0
  permission_handler: ^10.4.1
  device_info_plus: ^9.0.2
  package_info_plus: ^4.0.2
  firebase_messaging: ^14.6.4
  flutter_local_notifications: ^15.0.0
  flutter_html: ^3.0.0-alpha.6
  file_picker: ^5.3.2
  path_provider: ^2.0.15
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.0.0+2

  flutter_staggered_grid_view: ^0.6.2
  qr_flutter: ^4.1.0
  syncfusion_flutter_datepicker: ^20.4.44
  url_launcher: ^6.1.14
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0

  flutter_rating_bar: ^4.0.1
  myfatoorah_flutter: ^3.0.7
  form_builder_validators: ^9.1.0
  flutter_form_builder: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2


flutter:

  uses-material-design: true


  assets:

    # icon paths
    - assets/icons/
    - assets/icons/auth/
    - assets/icons/payment_method/
    - assets/icons/general/
    - assets/icons/home/
    - assets/icons/settings/
    - assets/icons/profile/
    - assets/icons/cart_and_checkout/

    # image path
    - assets/images/auth/
    - assets/images/general/
    - assets/images/about_us/
    - assets/images/test/
    # GIF
    - assets/gif/
    - assets/font/

  fonts:
    - family: CustomAppleLogo
      fonts:
        - asset: assets/font/CustomAppleLogo.ttf